export const opcoesEspecialidades = {
  /**
   * Lista de todas as especialidades médicas.
   */
  especialidadesMedicas: [
    { label: 'Alergologista', value: 'ALERGOLOGISTA' },
    { label: 'Angiologista', value: 'ANGIOLOGISTA' },
    { label: 'Cardiologista', value: 'CARDIOLOGISTA' },
    { label: 'Cirurgião Geral', value: 'CIRURGIAO_GERAL' },
    { label: 'Consulta Oftalmológica (Refração)', value: 'CONSULTA_OFTALMOLOGICA_REFRACAO' },
    { label: 'Dermatologista', value: 'DERMATOLOGISTA' },
    { label: 'Endocrinologista', value: 'ENDOCRINOLOGISTA' },
    { label: 'Gastroenterologista', value: 'GASTROENTEROLOGISTA' },
    { label: 'Hematologista', value: 'HEMATOLOGISTA' },
    { label: 'Mastologista', value: 'MASTOLOGISTA' },
    { label: 'Nefrologista', value: 'NEFROLOGISTA' },
    { label: 'Neurologista', value: 'NEUROLOGISTA' },
    { label: 'Neuropediatria', value: 'NEUROPEDIATRIA' },
    { label: 'Oftalmologista', value: 'OFTALMOLOGISTA' },
    { label: 'Ortopedista', value: 'ORTOPEDISTA' },
    { label: 'Otorrinolaringologista', value: 'OTORRINOLARINGOLOGISTA' },
    { label: 'Pediatra', value: 'PEDIATRIA' },
    { label: 'Pneumologista', value: 'PNEUMOLOGISTA' },
    { label: 'Reumatologista', value: 'REUMATOLOGISTA' },
    { label: 'Urologista', value: 'UROLOGISTA' },
  ],

  /**
   * Lista de todos os exames e procedimentos.
   */
  examesEProcedimentos: [
    { label: 'ASLO', value: 'ASLO' },
    { label: 'Ácido Úrico', value: 'ACIDO_URICO' },
    { label: 'Análise de Caracteres Físicos, Elementos e Sedimento da Urina', value: 'ANALISE_CARACTERES_FISICOS_ELEMENTOS_SEDIMENTO_URINA' },
    { label: 'Angioressonância Cerebral Arterial', value: 'ANGIORESSONANCIA_CEREBRAL_ARTERIAL' },
    { label: 'Angioressonância de Crânio Arterial', value: 'ANGIORESSONANCIA_DE_CRANIO_ARTERIAL' },
    { label: 'Anti-HBs', value: 'ANTI_HBS' },
    { label: 'Anti-HCV', value: 'ANTI_HCV' },
    { label: 'Antibiograma', value: 'ANTIBIOGRAMA' },
    { label: 'Audiometria Tonal e Vocal', value: 'AUDIOMETRIA_TONAL_LIMIAR_COM_TESTES_DE_DISCRIMINACAO' },
    { label: 'Avaliação Urodinâmica Completa', value: 'AVALIACAO_URODINAMICA_COMPLETA' },
    { label: 'Baciloscopia de Escarro (BAAR)', value: 'BACILOSCOPIA_DE_ESCARRO_BAAR' },
    { label: 'Baciloscopia Direta p/ BAAR Tuberculose (Controle)', value: 'BACILOSCOPIA_DIRETA_BAAR_TUBERCULOS_CONTROLE' },
    { label: 'Baciloscopia p/ BAAR Direta Tuberculose (Diagnóstica)', value: 'BACILOSCOPIA_DIRETA_BAAR_TUBERCULOSE_DIAGNOSTICA' },
    { label: 'Bacterioscopia (Gram)', value: 'BACTEROSCOPIA_GRAM' },
    { label: 'Bilirrubina total e frações', value: 'BILIRRUBINA_TOTAL_FRACOES' },
    { label: 'Biópsia de Colo Uterino', value: 'BIOPSIA_COLO_UTERINO' },
    { label: 'Cálcio', value: 'CALCIO' },
    { label: 'Cateterismo', value: 'CATETERISMO' },
    { label: 'Cateterismo Cardíaco Diagnóstico', value: 'CATETERISMO_CARDIACO_ESQUERDO_DIAGNOSTICO' },
    { label: 'Cintilografia', value: 'CINTILOGRAFIA' },
    { label: 'Cintilografia Miocárdio (Repouso/Estresse)', value: 'CINTILOGRAFIA_MIOCARDIO_PERFUSAO_REPOUSO_ESTRESSE' },
    { label: 'Cintilografia Óssea', value: 'CINTILOGRAFIA_OSSEA' },
    { label: 'Cintilografia Tireoide com Captação', value: 'CINTILOGRAFIA_TIREOIDE_CAPTACAO' },
    { label: 'Clearance de Creatinina', value: 'CLEARANCE_CREATININA' },
    { label: 'Coagulograma', value: 'COAGULOGRAMA' },
    { label: 'Colesterol Total', value: 'COLESTEROL_TOTAL' },
    { label: 'Colonoscopia', value: 'COLONOSCOPIA' },
    { label: 'Colonoscopia com Biópsia', value: 'COLONOSCOPIA_COM_BIOPSIA' },
    { label: 'Colposcopia', value: 'COLPOSCOPIA' },
    { label: 'Contagem de Plaquetas', value: 'CONTAGEM_PLAQUETAS' },
    { label: 'Contagem de Reticulócitos', value: 'CONTAGEM_RETICULOCITOS' },
    { label: 'Creatinina', value: 'CREATININA' },
    { label: 'Cultura de Bactérias p/ Identificação (Urocultura)', value: 'CULTURA_BACTERIAS_IDENTIFICACAO_UROCULTURA' },
    { label: 'Cultura de Escarro', value: 'CULTURA_DE_ESCARRO' },
    { label: 'Densitometria Óssea', value: 'DENSITOMETRIA_OSSEA_COLUNA_E_FEMUR' },
    { label: 'Determinação de Capacidade de Fixação do Ferro', value: 'DETERMINACAO_CAPACIDADE_FIXACAO_FERRO' },
    { label: 'Determinação de Curva Glicêmica (2 Dosagens)', value: 'DETERMINACAO_CURVA_GLICEMICA_2_DOSAGENS' },
    { label: 'Determinação de Látex', value: 'DETERMINACAO_LATEX' },
    { label: 'Determinação de Tempo de Coagulação', value: 'DETERMINACAO_TEMPO_COAGULACAO' },
    { label: 'Determinação de Tempo de Sangramento de Ivy', value: 'DETERMINACAO_TEMPO_SANGRAMENTO_IVY' },
    { label: 'Determinação de Tempo de Sangramento-Duke', value: 'DETERMINACAO_TEMPO_SANGRAMENTO_DUKE' },
    { label: 'Determinação de Tempo de Trombina', value: 'DETERMINACAO_TEMPO_TROMBINA' },
    { label: 'Determinação de Velocidade de Hemossedimentação (VHS)', value: 'DETERMINACAO_VELOCIDADE_HEMOSSEDIMENTACAO_VHS' },
    { label: 'Determinação Direta e Reversa de Grupo ABO', value: 'DETERMINACAO_DIRETA_REVERSA_GRUPO_ABO' },
    { label: 'Determinação Quantitativa de Proteína C Reativa', value: 'DETERMINACAO_QUANTITATIVA_PROTEINA_C_REATIVA' },
    { label: 'Doppler', value: 'DOPPLER' },
    { label: 'Dosagem de 25 Hidroxivitamina D', value: 'DOSAGEM_25_HIDROXIVITAMINA_D' },
    { label: 'Dosagem de Albumina', value: 'DOSAGEM_ALBUMINA' },
    { label: 'Dosagem de Alfa-1-Antitripsina', value: 'DOSAGEM_ALFA_1_ANTITRIPSINA' },
    { label: 'Dosagem de Alfa-Fetoproteína', value: 'DOSAGEM_ALFA_FETOPROTEINA' },
    { label: 'Dosagem de Amilase', value: 'DOSAGEM_AMILASE' },
    { label: 'Dosagem de Cálcio Ionizável', value: 'DOSAGEM_CALCIO_IONIZAVEL' },
    { label: 'Dosagem de Complemento C3', value: 'DOSAGEM_COMPLEMENTO_C3' },
    { label: 'Dosagem de Complemento C4', value: 'DOSAGEM_COMPLEMENTO_C4' },
    { label: 'Dosagem de Cortisol', value: 'DOSAGEM_CORTISOL' },
    { label: 'Dosagem de Creatinofosfoquinase (CPK)', value: 'DOSAGEM_CREATINOFOSFOQUINASE_CPK' },
    { label: 'Dosagem de Creatinofosfoquinase Fração MB', value: 'DOSAGEM_CREATINOFOSFOQUINASE_FRACAO_MB' },
    { label: 'Dosagem de Dehidroepiandrosterona (DHEA)', value: 'DOSAGEM_DEHIDROEPIANDROSTERONA_DHEA' },
    { label: 'Dosagem de Desidrogenase Lática', value: 'DOSAGEM_DESIDROGENASE_LATICA' },
    { label: 'Dosagem de Estradiol', value: 'DOSAGEM_ESTRADIOL' },
    { label: 'Dosagem de Estriol', value: 'DOSAGEM_ESTRIOL' },
    { label: 'Dosagem de Estrona', value: 'DOSAGEM_ESTRONA' },
    { label: 'Dosagem de Ferritina', value: 'DOSAGEM_FERRITINA' },
    { label: 'Dosagem de Ferro Sérico', value: 'DOSAGEM_FERRO_SERICO' },
    { label: 'Dosagem de Fosfatase Ácida Total', value: 'DOSAGEM_FOSFATASE_ACIDA_TOTAL' },
    { label: 'Dosagem de Fósforo', value: 'DOSAGEM_FOSFORO' },
    { label: 'Dosagem de Gonadotrofina Coriônica Humana (HCG, Beta HCG)', value: 'DOSAGEM_GONADOTROFINA_CORIONICA_HUMANA_HCG_BETA_HCG' },
    { label: 'Dosagem de Haptoglobina', value: 'DOSAGEM_HAPTOGLOBINA' },
    { label: 'Dosagem de Hemoglobina', value: 'DOSAGEM_HEMOGLOBINA' },
    { label: 'Dosagem de Hemoglobina Glicosilada', value: 'DOSAGEM_HEMOGLOBINA_GLICOSILADA' },
    { label: 'Dosagem de Hormônio Folículo-Estimulante (FSH)', value: 'DOSAGEM_HORMONIO_FOLICULO_ESTIMULANTE_FSH' },
    { label: 'Dosagem de Hormônio Luteinizante (LH)', value: 'DOSAGEM_HORMONIO_LUTEINIZANTE_LH' },
    { label: 'Dosagem de Imunoglobulina A (IGA)', value: 'DOSAGEM_IMUNOGLOBULINA_A_IGA' },
    { label: 'Dosagem de Imunoglobulina E (IGE)', value: 'DOSAGEM_IMUNOGLOBULINA_E_IGE' },
    { label: 'Dosagem de Imunoglobulina M (IGM)', value: 'DOSAGEM_IMUNOGLOBULINA_M_IGM' },
    { label: 'Dosagem de Insulina', value: 'DOSAGEM_INSULINA' },
    { label: 'Dosagem de Lactato', value: 'DOSAGEM_LACTATO' },
    { label: 'Dosagem de Lipase', value: 'DOSAGEM_LIPASE' },
    { label: 'Dosagem de Lítio', value: 'DOSAGEM_LITIO' },
    { label: 'Dosagem de Magnésio', value: 'DOSAGEM_MAGNESIO' },
    { label: 'Dosagem de Microalbumina na Urina', value: 'DOSAGEM_MICROALBUMINA_NA_URINA' },
    { label: 'Dosagem de Muco-Proteínas', value: 'DOSAGEM_MUCO_PROTEINAS' },
    { label: 'Dosagem de Paratormônio', value: 'DOSAGEM_PARATORMONIO' },
    { label: 'Dosagem de Progesterona', value: 'DOSAGEM_PROGESTERONA' },
    { label: 'Dosagem de Prolactina', value: 'DOSAGEM_PROLACTINA' },
    { label: 'Dosagem de Proteínas (Urina de 24 Horas)', value: 'DOSAGEM_PROTEINAS_URINA_24_HORAS' },
    { label: 'Dosagem de Proteínas Totais', value: 'DOSAGEM_PROTEINAS_TOTAIS' },
    { label: 'Dosagem de Proteínas Totais e Frações', value: 'DOSAGEM_PROTEINAS_TOTAIS_E_FRACOES' },
    { label: 'Dosagem de Sulfato de Hidroepiandrosterona (DHEAS)', value: 'DOSAGEM_SULFATO_DE_HIDROEPIANDROSTERONA_DHEAS' },
    { label: 'Dosagem de Testosterona', value: 'DOSAGEM_TESTOSTERONA' },
    { label: 'Dosagem de Testosterona Livre', value: 'DOSAGEM_TESTOSTERONA_LIVRE' },
    { label: 'Dosagem de Tireoglobulina', value: 'DOSAGEM_TIREOGLOBULINA' },
    { label: 'Dosagem de Tiroxina (T4)', value: 'DOSAGEM_TIROXINA_T4' },
    { label: 'Dosagem de Transferrina', value: 'DOSAGEM_TRANSFERRINA' },
    { label: 'Dosagem de Triiodotironina (T3)', value: 'DOSAGEM_TRIIODOTIRONINA_T3' },
    { label: 'Dosagem de Troponina', value: 'DOSAGEM_TROPONINA' },
    { label: 'Dosagem de Vitamina B12', value: 'DOSAGEM_VITAMINA_B12' },
    { label: 'Dosagem de Zinco', value: 'DOSAGEM_ZINCO' },
    { label: 'Ecocardiograma Transtorácico com Doppler', value: 'ECOCARDIOGRAMA_TRANSTORACICO_MODO_M_BIDIMENSIONAL_DOPPLER' },
    { label: 'Eletrocardiograma (ECG)', value: 'ELETROCARDIOGRAMA_ECG' },
    { label: 'Eletroencefalograma Convencional', value: 'ELETROENCEFALOGRAMA_CONVENCIONAL' },
    { label: 'Eletroforese de Hemoglobina', value: 'ELETROFORESE_DE_HEMOGLOBINA' },
    { label: 'Eletroforese de Lipoproteínas', value: 'ELETROFORESE_DE_LIPOPROTEINAS' },
    { label: 'Eletroneuromiografia', value: 'ELETRONEUROMIOGRAFIA' },
    { label: 'Eletroneuromiografia MMII', value: 'ELETRONEUROMIOGRAFIA_MEMBROS_INFERIORES' },
    { label: 'Eletroneuromiografia MMSS', value: 'ELETRONEUROMIOGRAFIA_MEMBROS_SUPERIORES' },
    { label: 'Endoscopia Digestiva Alta', value: 'ENDOSCOPIA_DIGESTIVA_ALTA' },
    { label: 'Endoscopia Digestiva Alta com Biópsia', value: 'ENDOSCOPIA_DIGESTIVA_ALTA_COM_BIOPSIA' },
    { label: 'Eritrograma (Eritrócitos, Hemoglobina, Hematócrito)', value: 'ERITROGRAMA' },
    { label: 'Espirometria Completa', value: 'ESPIROMETRIA_PROVA_VENTILATORIA_COMPLETA' },
    { label: 'Exame de Caracteres Físicos, Contagem Global e Específica de Células', value: 'EXAME_CARACTERES_FISICOS_CONTAGEM_GLOBAL_ESPECIFICA_CELULAS' },
    { label: 'Exerese Pequenas Lesões de Pele + AP', value: 'EXERESE_PEQUENAS_LESOES_PELE_ANATOMOPATOLOGICO' },
    { label: 'Fator Reumatoide', value: 'FATOR_REUMATOIDE' },
    { label: 'Fosfatase Alcalina', value: 'FOSFATASE_ALCALINA' },
    { label: 'Fundoscopia Binocular Indireta', value: 'FUNDOSCOPIA_BINOCULAR_INDIRETA' },
    { label: 'Gama GT', value: 'GAMA_GT' },
    { label: 'Glicemia de Jejum', value: 'GLICEMIA_JEJUM' },
    { label: 'HBsAg', value: 'HBSAG' },
    { label: 'HDL Colesterol', value: 'HDL_COLESTEROL' },
    { label: 'Hematócrito', value: 'HEMATOCRITO' },
    { label: 'Hemocultura', value: 'HEMOCULTURA' },
    { label: 'Hemoglobina Glicada (HbA1c)', value: 'HEMOGLOBINA_GLICADA_HBA1C' },
    { label: 'Hemograma Completo', value: 'HEMOGRAMA_COMPLETO' },
    { label: 'Holter', value: 'HOLTER' },
    { label: 'Holter 24 Horas (3 Canais)', value: 'HOLTER_24_HORAS_3_CANAIS' },
    { label: 'Impedanciometria', value: 'IMPEDANCIOMETRIA' },
    { label: 'Imunoeletroforese de Proteínas', value: 'IMUNOELETROFORESE_DE_PROTEINAS' },
    { label: 'LDL Colesterol', value: 'LDL_COLESTEROL' },
    { label: 'Leucograma', value: 'LEUCOGRAMA' },
    { label: 'M.A.P.A.', value: 'MAPA' },
    { label: 'MAPA 24 Horas', value: 'MAPA_24_HORAS_MONITORIZACAO_AMBULATORIAL_PRESSAO_ARTERIAL' },
    { label: 'Mamografia', value: 'MAMOGRAFIA' },
    { label: 'Mamografia Bilateral', value: 'MAMOGRAFIA_BILATERAL' },
    { label: 'PSA Livre', value: 'PSA_LIVRE' },
    { label: 'PSA Total', value: 'PSA_TOTAL' },
    { label: 'Parasitológico de Fezes', value: 'PARASITOLOGICO_DE_FEZES' },
    { label: 'Pesquisa de Anticorpo IGG Anticardiolipina', value: 'PESQUISA_ANTICORPO_IGG_ANTICARDIOLIPINA' },
    { label: 'Pesquisa de Anticorpo IGM de Anticardiolipina', value: 'PESQUISA_ANTICORPO_IGM_DE_ANTICARDIOLIPINA' },
    { label: 'Pesquisa de Anticorpos Anti-Helicobacter Pylori', value: 'PESQUISA_ANTICORPOS_ANTI_HELICOBACTER_PYLORI' },
    { label: 'Pesquisa de Anticorpos Anti-HIV-1+ HIV-2 (ELISA)', value: 'PESQUISA_ANTICORPOS_ANTI_HIV_1_HIV_2_ELISA' },
    { label: 'Pesquisa de Anticorpos Anti-HTLV-1 HTLV-2', value: 'PESQUISA_ANTICORPOS_ANTI_HTLV_1_HTLV_2' },
    { label: 'Pesquisa de Anticorpos Anti-SM', value: 'PESQUISA_ANTICORPOS_ANTI_SM' },
    { label: 'Pesquisa de Anticorpos Anti-SS-A (RO)', value: 'PESQUISA_ANTICORPOS_ANTI_SS_A_RO' },
    { label: 'Pesquisa de Anticorpos Anti-SS-B (LA)', value: 'PESQUISA_ANTICORPOS_ANTI_SS_B_LA' },
    { label: 'Pesquisa de Anticorpos Antinúcleo', value: 'PESQUISA_ANTICORPOS_ANTINUCLEO' },
    { label: 'Pesquisa de Anticorpos Antitireoglobulina', value: 'PESQUISA_ANTICORPOS_ANTITIREOGLOBULINA' },
    { label: 'Pesquisa de Anticorpos Contra Antígeno E do Vírus da Hepatite B (Anti-HBE)', value: 'PESQUISA_ANTICORPOS_CONTRA_ANTIGENO_E_VIRUS_HEPATITE_B_ANTI_HBE' },
    { label: 'Pesquisa de Anticorpos Contra o Vírus da Hepatite D (Anti-HDV)', value: 'PESQUISA_ANTICORPOS_CONTRA_VIRUS_HEPATITE_D_ANTI_HDV' },
    { label: 'Pesquisa de Anticorpos Contra o Vírus do Sarampo', value: 'PESQUISA_ANTICORPOS_CONTRA_VIRUS_SARAMPO' },
    { label: 'Pesquisa de Anticorpos IGG Anticitomegalovírus', value: 'PESQUISA_ANTICORPOS_IGG_ANTICITOMEGALOVIRUS' },
    { label: 'Pesquisa de Anticorpos IGG Antileishmanias', value: 'PESQUISA_ANTICORPOS_IGG_ANTILEISHMANIAS' },
    { label: 'Pesquisa de Anticorpos IGG Antitoxoplasma', value: 'PESQUISA_ANTICORPOS_IGG_ANTITOXOPLASMA' },
    { label: 'Pesquisa de Anticorpos IGG Antitrypanosoma Cruzi', value: 'PESQUISA_ANTICORPOS_IGG_ANTITRYPANOSOMA_CRUZI' },
    { label: 'Pesquisa de Anticorpos IGG Contra Antígeno Central do Vírus da Hepatite B (Anti-HBC-IGG)', value: 'PESQUISA_ANTICORPOS_IGG_CONTRA_ANTIGENO_CENTRAL_VIRUS_HEPATITE_B_ANTI_HBC_IGG' },
    { label: 'Pesquisa de Anticorpos IGG Contra o Vírus da Hepatite A (HAV-IGG)', value: 'PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_HEPATITE_A_HAV_IGG' },
    { label: 'Pesquisa de Anticorpos IGG Contra o Vírus da Rubéola', value: 'PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_RUBEOLA' },
    { label: 'Pesquisa de Anticorpos IGG Contra o Vírus da Varicela-Herpes Zoster', value: 'PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_VARICELA_HERPES_ZOSTER' },
    { label: 'Pesquisa de Anticorpos IGG Contra o Vírus Epstein-Barr', value: 'PESQUISA_ANTICORPOS_IGG_CONTRA_VIRUS_EPSTEIN_BARR' },
    { label: 'Pesquisa de Anticorpos IGM Anticitomegalovírus', value: 'PESQUISA_ANTICORPOS_IGM_ANTICITOMEGALOVIRUS' },
    { label: 'Pesquisa de Anticorpos IGM Antileishmanias', value: 'PESQUISA_ANTICORPOS_IGM_ANTILEISHMANIAS' },
    { label: 'Pesquisa de Anticorpos IGM Antitoxoplasma', value: 'PESQUISA_ANTICORPOS_IGM_ANTITOXOPLASMA' },
    { label: 'Pesquisa de Anticorpos IGM Antitrypanosoma Cruzi', value: 'PESQUISA_ANTICORPOS_IGM_ANTITRYPANOSOMA_CRUZI' },
    { label: 'Pesquisa de Anticorpos IGM Contra Antígeno Central do Vírus da Hepatite B (Anti-HBC-IGM)', value: 'PESQUISA_ANTICORPOS_IGM_CONTRA_ANTIGENO_CENTRAL_VIRUS_HEPATITE_B_ANTI_HBC_IGM' },
    { label: 'Pesquisa de Anticorpos IGM Contra o Vírus da Hepatite A (HAV-IGG)', value: 'PESQUISA_ANTICORPOS_IGM_CONTRA_VIRUS_HEPATITE_A_HAV_IGG' },
    { label: 'Pesquisa de Anticorpos IGM Contra o Vírus da Rubéola', value: 'PESQUISA_ANTICORPOS_IGM_CONTRA_VIRUS_RUBEOLA' },
    { label: 'Pesquisa de Antígeno Carcinoembrionário (CEA)', value: 'PESQUISA_ANTIGENO_CARCINOEMBRIONARIO_CEA' },
    { label: 'Pesquisa de Antígeno E do Vírus da Hepatite B (HBEAG)', value: 'PESQUISA_ANTIGENO_E_VIRUS_HEPATITE_B_HBEAG' },
    { label: 'Pesquisa de Fator RH (Inclui D Fraco)', value: 'PESQUISA_FATOR_RH_INCLUI_D_FRACO' },
    { label: 'Pesquisa de Fator Reumatoide (Waaler-Rose)', value: 'PESQUISA_FATOR_REUMATOIDE_WAALER_ROSE' },
    { label: 'Pesquisa de Hemoglobina S', value: 'PESQUISA_HEMOGLOBINA_S' },
    { label: 'Pesquisa de Larvas nas Fezes', value: 'PESQUISA_LARVAS_NAS_FEZES' },
    { label: 'Pesquisa de Ovos, Cistos e Parasitas', value: 'PESQUISA_OVOS_CISTOS_PARASITAS' },
    { label: 'Pesquisa de Sangue Oculto nas Fezes', value: 'PESQUISA_SANGUE_OCULTO_FEZES' },
    { label: 'Pesquisa de Tripanossoma', value: 'PESQUISA_TRIPANOSSOMA' },
    { label: 'Pesquisa de Trofozoitas nas Fezes', value: 'PESQUISA_TROFOZOITAS_NAS_FEZES' },
    { label: 'Potássio', value: 'POTASSIO' },
    { label: 'Prova de Retração do Coágulo', value: 'PROVA_RETRACAO_COAGULO' },
    { label: 'Prova do Laço', value: 'PROVA_DO_LACO' },
    { label: 'RM Coluna Cervical', value: 'RESSONANCIA_MAGNETICA_COLUNA_CERVICAL' },
    { label: 'RM Coluna Lombar', value: 'RESSONANCIA_MAGNETICA_COLUNA_LOMBAR' },
    { label: 'RM Crânio/Encéfalo', value: 'RESSONANCIA_MAGNETICA_CRANIO_ENCEFALO' },
    { label: 'RM Joelho', value: 'RESSONANCIA_MAGNETICA_JOELHO' },
    { label: 'Raio-X Abdômen Agudo', value: 'RAIO_X_ABDOMEN_AGUDO' },
    { label: 'Raio-X Abdômen Simples', value: 'RAIO_X_ABDOMEN_SIMPLES' },
    { label: 'Raio-X Bacia', value: 'RAIO_X_ARTICULACAO_COXO_FEMURAL_BACIA' },
    { label: 'Raio-X Coluna Cervical', value: 'RAIO_X_COLUNA_CERVICAL' },
    { label: 'Raio-X Coluna Dorsal', value: 'RAIO_X_COLUNA_DORSAL' },
    { label: 'Raio-X Coluna Lombo-Sacra', value: 'RAIO_X_COLUNA_LOMBO_SACRA' },
    { label: 'Raio-X Joelho', value: 'RAIO_X_JOELHO' },
    { label: 'Raio-X Mão/Quirodáctilos', value: 'RAIO_X_MAO_OU_QUIRODACTILOS' },
    { label: 'Raio-X Pé/Pododáctilos', value: 'RAIO_X_PE_OU_PODODACTILOS' },
    { label: 'Raio-X Seios da Face', value: 'RAIO_X_SEIOS_DA_FACE' },
    { label: 'Raio-X Tórax PA', value: 'RAIO_X_TORAX_PA' },
    { label: 'Raio-X Tórax PA/Perfil', value: 'RAIO_X_TORAX_PA_PERFIL' },
    { label: 'Reação de Hemaglutinação (TPHA) p/ Diagnóstico da Sífilis', value: 'REACAO_HEMAGLUTINACAO_TPHA_DIAGNOSTICO_SIFILIS' },
    { label: 'Reação de Montenegro ID', value: 'REACAO_MONTENEGRO_ID' },
    { label: 'Ressonância Magnética', value: 'RESSONANCIA' },
    { label: 'Ressonância Magnética de Articulação Têmporo-Mandibular Bilateral', value: 'RESSONANCIA_MAGNETICA_ARTICULACAO_TEMPORO_MANDIBULAR_BILATERAL' },
    { label: 'Ressonância Magnética Bacia/Pelve/Abdômen Inferior', value: 'RESSONANCIA_MAGNETICA_BACIA_PELVE_ABDOMEN_INFERIOR' },
    { label: 'Ressonância Magnética de Coluna Torácica', value: 'RESSONANCIA_MAGNETICA_COLUNA_TORACICA' },
    { label: 'Ressonância Magnética de Coração / Aorta c/ Cine', value: 'RESSONANCIA_MAGNETICA_CORACAO_AORTA_COM_CINE' },
    { label: 'Ressonância Magnética de Membro Inferior (Unilateral)', value: 'RESSONANCIA_MAGNETICA_MEMBRO_INFERIOR_UNILATERAL' },
    { label: 'Ressonância Magnética de Membro Superior (Unilateral)', value: 'RESSONANCIA_MAGNETICA_MEMBRO_SUPERIOR_UNILATERAL' },
    { label: 'Ressonância Magnética de Sela Túrcica', value: 'RESSONANCIA_MAGNETICA_SELA_TURCICA' },
    { label: 'Ressonância Magnética de Tórax', value: 'RESSONANCIA_MAGNETICA_TORAX' },
    { label: 'Ressonância Magnética de Vias Biliares / Colangioressonância', value: 'RESSONANCIA_MAGNETICA_VIAS_BILIARES_COLANGIORESSONANCIA' },
    { label: 'Sódio', value: 'SODIO' },
    { label: 'Sorologia para HIV', value: 'SOROLOGIA_HIV' },
    { label: 'Sumário de Urina (EAS)', value: 'SUMARIO_DE_URINA_EAS' },
    { label: 'T4 Livre', value: 'T4_LIVRE' },
    { label: 'TC Abdômen Total', value: 'TOMOGRAFIA_COMPUTADORIZADA_ABDOMEN_TOTAL' },
    { label: 'TC Crânio', value: 'TOMOGRAFIA_COMPUTADORIZADA_CRANIO' },
    { label: 'TC Tórax', value: 'TOMOGRAFIA_COMPUTADORIZADA_TORAX' },
    { label: 'TGO', value: 'TGO' },
    { label: 'TGP', value: 'TGP' },
    { label: 'TP', value: 'TP' },
    { label: 'TSH', value: 'TSH_HORMONIO_TIREOESTIMULANTE' },
    { label: 'TTPA', value: 'TTPA' },
    { label: 'Teste de VDRL p/ Detecção de Sífilis', value: 'TESTE_VDRL_DETECCAO_SIFILIS' },
    { label: 'Teste Direto de Antiglobulina Humana (TAD)', value: 'TESTE_DIRETO_ANTIGLOBULINA_HUMANA_TAD' },
    { label: 'Teste Ergométrico', value: 'TESTE_ERGOMETRICO' },
    { label: 'Teste Ergométrico Convencional', value: 'TESTE_ERGOMETRICO_CONVENCIONAL' },
    { label: 'Teste FTA-ABS IGG p/ Diagnóstico da Sífilis', value: 'TESTE_FTA_ABS_IGG_DIAGNOSTICO_SIFILIS' },
    { label: 'Teste FTA-ABS IGM p/ Diagnóstico da Sífilis', value: 'TESTE_FTA_ABS_IGM_DIAGNOSTICO_SIFILIS' },
    { label: 'Teste Rápido de Gravidez (TIG)', value: 'TESTE_RAPIDO_GRAVIDEZ_TIG' },
    { label: 'Teste Rápido para Hepatite B', value: 'TESTE_RAPIDO_HEPATITE_B' },
    { label: 'Teste Rápido para Hepatite C', value: 'TESTE_RAPIDO_HEPATITE_C' },
    { label: 'Teste Rápido para HIV', value: 'TESTE_RAPIDO_HIV' },
    { label: 'Teste Rápido para Sífilis', value: 'TESTE_RAPIDO_SIFILIS' },
    { label: 'Teste Tuberculínico(PPD)', value: 'TESTE_TUBERCULINICO_PPD' },
    { label: 'Tipo Sanguíneo', value: 'TIPO_SANGUINEO' },
    { label: 'Tomografia Computadorizada', value: 'TOMOGRAFIA' },
    { label: 'Tomografia Computadorizada de Articulações de Membro Inferior', value: 'TOMOGRAFIA_COMPUTADORIZADA_ARTICULACOES_MEMBRO_INFERIOR' },
    { label: 'Tomografia Computadorizada de Articulações de Membro Superior', value: 'TOMOGRAFIA_COMPUTADORIZADA_ARTICULACOES_MEMBRO_SUPERIOR' },
    { label: 'Tomografia Computadorizada de Coluna Cervical com ou sem Contraste', value: 'TOMOGRAFIA_COMPUTADORIZADA_COLUNA_CERVICAL_COM_OU_SEM_CONTRASTE' },
    { label: 'Tomografia Computadorizada de Coluna Lombosacra com ou sem Contraste', value: 'TOMOGRAFIA_COMPUTADORIZADA_COLUNA_LOMBOSACRA_COM_OU_SEM_CONTRASTE' },
    { label: 'Tomografia Computadorizada de Coluna Torácica com ou sem Contraste', value: 'TOMOGRAFIA_COMPUTADORIZADA_COLUNA_TORACICA_COM_OU_SEM_CONTRASTE' },
    { label: 'Tomografia Computadorizada de Face / Seios da Face / Articulações Têmporo-Mandibulares', value: 'TOMOGRAFIA_COMPUTADORIZADA_FACE_SEIOS_DA_FACE_ARTICULACOES_TEMPO_MANDIBULARES' },
    { label: 'Tomografia Computadorizada de Pelve / Bacia / Abdômen Inferior', value: 'TOMOGRAFIA_COMPUTADORIZADA_PELVE_BACIA_ABDOMEN_INFERIOR' },
    { label: 'Tomografia Computadorizada de Sela Túrcica', value: 'TOMOGRAFIA_COMPUTADORIZADA_SELA_TURCICA' },
    { label: 'Tomografia Computadorizada de Segmentos Apendiculares - Braço, Antebraço, Mão, Coxa, Perna, Pé', value: 'TOMOGRAFIA_COMPUTADORIZADA_SEGMENTOS_APENDICULARES' },
    { label: 'Tomografia Computadorizada do Pescoço', value: 'TOMOGRAFIA_COMPUTADORIZADA_PESCOCO' },
    { label: 'Tomografia por Emissão de Pósitrons - PET CT', value: 'TOMOGRAFIA_POR_EMISSAO_DE_POSITRONS_PET_CT' },
    { label: 'Tomomielografia Computadorizada', value: 'TOMOMIELOGRAFIA_COMPUTADORIZADA' },
    { label: 'Tonometria de Aplanação', value: 'TONOMETRIA_APLANACAO' },
    { label: 'Triglicerídeos', value: 'TRIGLICERIDEOS' },
    { label: 'USG Abdômen Superior', value: 'ULTRASSONOGRAFIA_ABDOMEN_SUPERIOR' },
    { label: 'USG Abdominal Total', value: 'ULTRASSONOGRAFIA_ABDOMINAL_TOTAL' },
    { label: 'USG Articular', value: 'ULTRASSONOGRAFIA_ARTICULAR' },
    { label: 'USG Doppler Arterial MI Bilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_BILATERAL' },
    { label: 'USG Doppler Arterial MI Unilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_UNILATERAL' },
    { label: 'USG Doppler Carótidas e Vertebrais', value: 'ULTRASSONOGRAFIA_DOPPLER_CAROTIDAS_E_VERTEBRAIS' },
    { label: 'USG Doppler Venoso MI Bilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_BILATERAL' },
    { label: 'USG Doppler Venoso MI Unilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_UNILATERAL' },
    { label: 'USG Obstétrica', value: 'ULTRASSONOGRAFIA_OBSTETRICA' },
    { label: 'USG Partes Mole', value: 'ULTRASSONOGRAFIA_PARTES_MOLES' },
    { label: 'USG Pélvica (Abdominal)', value: 'ULTRASSONOGRAFIA_PELVICA_VIA_ABDOMINAL' },
    { label: 'USG Pélvica (Transvaginal)', value: 'ULTRASSONOGRAFIA_PELVICA_TRANSVAGINAL' },
    { label: 'USG Próstata (Abdominal)', value: 'ULTRASSONOGRAFIA_PROSTATA_VIA_ABDOMINAL' },
    { label: 'USG Tireoide', value: 'ULTRASSONOGRAFIA_TIREOIDE' },
    { label: 'USG Vias Urinárias', value: 'ULTRASSONOGRAFIA_VIAS_URINARIAS' },
    { label: 'Ureia', value: 'UREIA' },
    { label: 'Urocultura com Antibiograma', value: 'UROCULTURA_COM_ANTIBIOGRAMA' },
    { label: 'VDRL', value: 'VDRL' },
    { label: 'VDRL p/ Detecção de Sífilis em Gestante', value: 'VDRL_DETECCAO_SIFILIS_EM_GESTANTE' },
    { label: 'VLDL Colesterol', value: 'VLDL_COLESTEROL' },
  ]
};