export const opcoesEspecialidades = {
  /**
   * Lista de todas as especialidades médicas.
   */
  especialidadesMedicas: [
    { label: 'Angiologista', value: 'ANGIOLOGISTA' },
    { label: 'Cardiologista', value: 'CARDIOLOGISTA' },
    { label: 'Cirurgião Geral', value: 'CIRURGIAO_GERAL'},
    { label: 'Consulta Oftalmológica (Refração)', value: 'CONSULTA_OFTALMOLOGICA_REFRACAO' },
    { label: 'Dermatologista', value: 'DERMATOLOGISTA' },
    { label: 'Endocrinologista', value: 'ENDOCRINOLOGISTA' },
    { label: 'Gastroenterologista', value: 'GASTROENTEROLOGISTA' },
    { label: 'Hematologista', value: 'HEMATOLOGISTA' },
    { label: 'Mastologista', value: 'MASTOLOGISTA' },
    { label: 'Nefrologista', value: 'NEFROLOGISTA' },
    { label: 'Neurologista', value: 'NEUROLOGISTA' },
    { label: 'Neuropediatria', value: 'NEUROPEDIATRIA' },
    { label: 'Oftalmologista', value: 'OFTALMOLOGISTA' },
    { label: 'Ortopedista', value: 'ORTOPEDISTA' },
    { label: 'Otorrinolaringologista', value: 'OTORRINOLARINGOLOGISTA' },
    { label: 'Pediatra', value: 'PEDIATRIA' },
    { label: 'Pneumologista', value: 'PNEUMOLOGISTA' },
    { label: 'Reumatologista', value: 'REUMATOLOGISTA' },
    { label: 'Urologista', value: 'UROLOGISTA' },
  ],

  /**
   * Lista de todos os exames e procedimentos.
   */
  examesEProcedimentos: [
    { label: 'ASLO', value: 'ASLO' },
    { label: 'Ácido Úrico', value: 'ACIDO_URICO' },
    { label: 'Anti-HBs', value: 'ANTI_HBS' },
    { label: 'Anti-HCV', value: 'ANTI_HCV' },
    { label: 'Audiometria Tonal e Vocal', value: 'AUDIOMETRIA_TONAL_LIMIAR_COM_TESTES_DE_DISCRIMINACAO' },
    { label: 'Avaliação Urodinâmica Completa', value: 'AVALIACAO_URODINAMICA_COMPLETA' },
    { label: 'Baciloscopia de Escarro (BAAR)', value: 'BACILOSCOPIA_DE_ESCARRO_BAAR' },
    { label: 'Bilirrubina total e frações', value: 'BILIRRUBINA_TOTAL_FRACOES' },
    { label: 'Biópsia de Colo Uterino', value: 'BIOPSIA_COLO_UTERINO' },
    { label: 'Cálcio', value: 'CALCIO' },
    { label: 'Cateterismo', value: 'CATETERISMO' },
    { label: 'Cateterismo Cardíaco Diagnóstico', value: 'CATETERISMO_CARDIACO_ESQUERDO_DIAGNOSTICO' },
    { label: 'Cintilografia', value: 'CINTILOGRAFIA' },
    { label: 'Cintilografia Miocárdio (Repouso/Estresse)', value: 'CINTILOGRAFIA_MIOCARDIO_PERFUSAO_REPOUSO_ESTRESSE' },
    { label: 'Cintilografia Óssea', value: 'CINTILOGRAFIA_OSSEA' },
    { label: 'Cintilografia Tireoide com Captação', value: 'CINTILOGRAFIA_TIREOIDE_CAPTACAO' },
    { label: 'Coagulograma', value: 'COAGULOGRAMA' },
    { label: 'Colesterol Total', value: 'COLESTEROL_TOTAL' },
    { label: 'Colonoscopia', value: 'COLONOSCOPIA' },
    { label: 'Colonoscopia com Biópsia', value: 'COLONOSCOPIA_COM_BIOPSIA' },
    { label: 'Colposcopia', value: 'COLPOSCOPIA' },
    { label: 'Creatinina', value: 'CREATININA' },
    { label: 'Cultura de Escarro', value: 'CULTURA_DE_ESCARRO' },
    { label: 'Densitometria Óssea', value: 'DENSITOMETRIA_OSSEA_COLUNA_E_FEMUR' },
    { label: 'Doppler', value: 'DOPPLER' },
    { label: 'Ecocardiograma Transtorácico com Doppler', value: 'ECOCARDIOGRAMA_TRANSTORACICO_MODO_M_BIDIMENSIONAL_DOPPLER' },
    { label: 'Eletrocardiograma (ECG)', value: 'ELETROCARDIOGRAMA_ECG' },
    { label: 'Eletroencefalograma Convencional', value: 'ELETROENCEFALOGRAMA_CONVENCIONAL' },
    { label: 'Eletroneuromiografia', value: 'ELETRONEUROMIOGRAFIA' },
    { label: 'Eletroneuromiografia MMII', value: 'ELETRONEUROMIOGRAFIA_MEMBROS_INFERIORES' },
    { label: 'Eletroneuromiografia MMSS', value: 'ELETRONEUROMIOGRAFIA_MEMBROS_SUPERIORES' },
    { label: 'Endoscopia Digestiva Alta', value: 'ENDOSCOPIA_DIGESTIVA_ALTA' },
    { label: 'Endoscopia Digestiva Alta com Biópsia', value: 'ENDOSCOPIA_DIGESTIVA_ALTA_COM_BIOPSIA' },
    { label: 'Espirometria Completa', value: 'ESPIROMETRIA_PROVA_VENTILATORIA_COMPLETA' },
    { label: 'Exerese Pequenas Lesões de Pele + AP', value: 'EXERESE_PEQUENAS_LESOES_PELE_ANATOMOPATOLOGICO' },
    { label: 'Fator Reumatoide', value: 'FATOR_REUMATOIDE' },
    { label: 'Fosfatase Alcalina', value: 'FOSFATASE_ALCALINA' },
    { label: 'Fundoscopia Binocular Indireta', value: 'FUNDOSCOPIA_BINOCULAR_INDIRETA' },
    { label: 'Gama GT', value: 'GAMA_GT' },
    { label: 'Glicemia de Jejum', value: 'GLICEMIA_JEJUM' },
    { label: 'HBsAg', value: 'HBSAG' },
    { label: 'HDL Colesterol', value: 'HDL_COLESTEROL' },
    { label: 'Hemoglobina Glicada (HbA1c)', value: 'HEMOGLOBINA_GLICADA_HBA1C' },
    { label: 'Hemograma Completo', value: 'HEMOGRAMA_COMPLETO' },
    { label: 'Holter', value: 'HOLTER' },
    { label: 'Holter 24 Horas (3 Canais)', value: 'HOLTER_24_HORAS_3_CANAIS' },
    { label: 'Impedanciometria', value: 'IMPEDANCIOMETRIA' },
    { label: 'LDL Colesterol', value: 'LDL_COLESTEROL' },
    { label: 'M.A.P.A.', value: 'MAPA' },
    { label: 'MAPA 24 Horas', value: 'MAPA_24_HORAS_MONITORIZACAO_AMBULATORIAL_PRESSAO_ARTERIAL' },
    { label: 'Mamografia', value: 'MAMOGRAFIA' },
    { label: 'Mamografia Bilateral', value: 'MAMOGRAFIA_BILATERAL' },
    { label: 'PSA Livre', value: 'PSA_LIVRE' },
    { label: 'PSA Total', value: 'PSA_TOTAL' },
    { label: 'Parasitológico de Fezes', value: 'PARASITOLOGICO_DE_FEZES' },
    { label: 'Pesquisa de Ovos, Cistos e Parasitas', value: 'PESQUISA_OVOS_CISTOS_PARASITAS' },
    { label: 'Pesquisa de Sangue Oculto nas Fezes', value: 'PESQUISA_SANGUE_OCULTO_FEZES' },
    { label: 'Potássio', value: 'POTASSIO' },
    { label: 'Raio-X Abdômen Agudo', value: 'RAIO_X_ABDOMEN_AGUDO' },
    { label: 'Raio-X Abdômen Simples', value: 'RAIO_X_ABDOMEN_SIMPLES' },
    { label: 'Raio-X Bacia', value: 'RAIO_X_ARTICULACAO_COXO_FEMURAL_BACIA' },
    { label: 'Raio-X Coluna Cervical', value: 'RAIO_X_COLUNA_CERVICAL' },
    { label: 'Raio-X Coluna Dorsal', value: 'RAIO_X_COLUNA_DORSAL' },
    { label: 'Raio-X Coluna Lombo-Sacra', value: 'RAIO_X_COLUNA_LOMBO_SACRA' },
    { label: 'Raio-X Joelho', value: 'RAIO_X_JOELHO' },
    { label: 'Raio-X Mão/Quirodáctilos', value: 'RAIO_X_MAO_OU_QUIRODACTILOS' },
    { label: 'Raio-X Pé/Pododáctilos', value: 'RAIO_X_PE_OU_PODODACTILOS' },
    { label: 'Raio-X Seios da Face', value: 'RAIO_X_SEIOS_DA_FACE' },
    { label: 'Raio-X Tórax PA', value: 'RAIO_X_TORAX_PA' },
    { label: 'Raio-X Tórax PA/Perfil', value: 'RAIO_X_TORAX_PA_PERFIL' },
    { label: 'Ressonância Magnética', value: 'RESSONANCIA' },
    { label: 'RM Crânio/Encéfalo', value: 'RESSONANCIA_MAGNETICA_CRANIO_ENCEFALO' },
    { label: 'RM Coluna Cervical', value: 'RESSONANCIA_MAGNETICA_COLUNA_CERVICAL' },
    { label: 'RM Coluna Lombar', value: 'RESSONANCIA_MAGNETICA_COLUNA_LOMBAR' },
    { label: 'RM Joelho', value: 'RESSONANCIA_MAGNETICA_JOELHO' },
    { label: 'Sódio', value: 'SODIO' },
    { label: 'Sorologia para HIV', value: 'SOROLOGIA_HIV' },
    { label: 'Sumário de Urina (EAS)', value: 'SUMARIO_DE_URINA_EAS' },
    { label: 'T4 Livre', value: 'T4_LIVRE' },
    { label: 'TC Abdômen Total', value: 'TOMOGRAFIA_COMPUTADORIZADA_ABDOMEN_TOTAL' },
    { label: 'TC Crânio', value: 'TOMOGRAFIA_COMPUTADORIZADA_CRANIO' },
    { label: 'TC Tórax', value: 'TOMOGRAFIA_COMPUTADORIZADA_TORAX' },
    { label: 'TGO', value: 'TGO' },
    { label: 'TGP', value: 'TGP' },
    { label: 'TP', value: 'TP' },
    { label: 'TSH', value: 'TSH_HORMONIO_TIREOESTIMULANTE' },
    { label: 'TTPA', value: 'TTPA' },
    { label: 'Teste Ergométrico', value: 'TESTE_ERGOMETRICO' },
    { label: 'Teste Ergométrico Convencional', value: 'TESTE_ERGOMETRICO_CONVENCIONAL' },
    { label: 'Teste Rápido de Gravidez (TIG)', value: 'TESTE_RAPIDO_GRAVIDEZ_TIG' },
    { label: 'Teste Rápido para Hepatite B', value: 'TESTE_RAPIDO_HEPATITE_B' },
    { label: 'Teste Rápido para Hepatite C', value: 'TESTE_RAPIDO_HEPATITE_C' },
    { label: 'Teste Rápido para HIV', value: 'TESTE_RAPIDO_HIV' },
    { label: 'Teste Rápido para Sífilis', value: 'TESTE_RAPIDO_SIFILIS' },
    { label: 'Tipo Sanguíneo', value: 'TIPO_SANGUINEO' },
    { label: 'Tomografia Computadorizada', value: 'TOMOGRAFIA' },
    { label: 'Tonometria de Aplanação', value: 'TONOMETRIA_APLANACAO' },
    { label: 'Triglicerídeos', value: 'TRIGLICERIDEOS' },
    { label: 'USG Abdômen Superior', value: 'ULTRASSONOGRAFIA_ABDOMEN_SUPERIOR' },
    { label: 'USG Abdominal Total', value: 'ULTRASSONOGRAFIA_ABDOMINAL_TOTAL' },
    { label: 'USG Articular', value: 'ULTRASSONOGRAFIA_ARTICULAR' },
    { label: 'USG Doppler Arterial MI Bilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_BILATERAL' },
    { label: 'USG Doppler Arterial MI Unilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_ARTERIAL_MEMBRO_INFERIOR_UNILATERAL' },
    { label: 'USG Doppler Carótidas e Vertebrais', value: 'ULTRASSONOGRAFIA_DOPPLER_CAROTIDAS_E_VERTEBRAIS' },
    { label: 'USG Doppler Venoso MI Bilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_BILATERAL' },
    { label: 'USG Doppler Venoso MI Unilateral', value: 'ULTRASSONOGRAFIA_DOPPLER_VENOSO_MEMBRO_INFERIOR_UNILATERAL' },
    { label: 'USG Obstétrica', value: 'ULTRASSONOGRAFIA_OBSTETRICA' },
    { label: 'USG Partes Mole', value: 'ULTRASSONOGRAFIA_PARTES_MOLES' },
    { label: 'USG Pélvica (Abdominal)', value: 'ULTRASSONOGRAFIA_PELVICA_VIA_ABDOMINAL' },
    { label: 'USG Pélvica (Transvaginal)', value: 'ULTRASSONOGRAFIA_PELVICA_TRANSVAGINAL' },
    { label: 'USG Próstata (Abdominal)', value: 'ULTRASSONOGRAFIA_PROSTATA_VIA_ABDOMINAL' },
    { label: 'USG Tireoide', value: 'ULTRASSONOGRAFIA_TIREOIDE' },
    { label: 'USG Vias Urinárias', value: 'ULTRASSONOGRAFIA_VIAS_URINARIAS' },
    { label: 'Ureia', value: 'UREIA' },
    { label: 'Urocultura com Antibiograma', value: 'UROCULTURA_COM_ANTIBIOGRAMA' },
    { label: 'VDRL', value: 'VDRL' },
    { label: 'VLDL Colesterol', value: 'VLDL_COLESTEROL' },
  ]
};