package io.github.regulacao_marcarcao.regulacao_marcacao.entity.enums;

public enum LocalDeAgendamentoEnum {
    
    POLICLINICA_RECONVALE,
    POLICLINICA_MUNICIPAL_DE_SANTO_ANTONIO_DE_JESUS,
    HOSPITAL_DE_CONCEICAO_DO_ALMEIDA,
    HOSPITAL_IRMA_DULCE,
    HOSPITAL_DA_MULHER,
    LABCHECAP,
    HOSPITAL_ROBERTO_SANTOS,
    HOSPITAL_LUIS_ARGOLO,
    HOSPITAL_DOS_OLHOS_BAHIA,
    CLINICA_A_MAIS_SAUDE,
    HOSPITAL_ARISTIDES,
    APAE,
    CDI,
    CEDAF,
    CLINICA_ELIZ,
    MULTICENTRO_DA_CARLOS_GOMES,
    MULTIIMAGEM,
    HOSPITAL_MUNICIPAL,
    HOSPITAL_ORTOPEDICO,
    HOSPITAL_DO_SUBURBIO,
    PRIMAGEM,
    PONTO_ALTO_IMAGEM,
    HOSPITAL_REGIONAL,
    HOSPITAL_SANTA_IZABEL;
}
