-- Criar a tabela para armazenar os CIDs
CREATE TABLE cid (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    codigo VARCHAR(255) NOT NULL UNIQUE,
    descricao VARCHAR(255)
);

-- Criar a tabela de junção para o relacionamento ManyToMany
CREATE TABLE solicitacao_cid (
    solicitacao_id BIGINT NOT NULL,
    cid_id BIGINT NOT NULL,
    PRIMARY KEY (solicitacao_id, cid_id),
    FOREIGN KEY (solicitacao_id) REFERENCES solicitacao(id),
    FOREIGN KEY (cid_id) REFERENCES cid(id)
);