-- Início do Bloco: V27__Adicionar_Carga_Massiva_Cids.sql

INSERT INTO cid (codigo, descricao) VALUES
('A00', 'Cólera'),
('A09', 'Diarréia e gastroenterite de origem infecciosa presumível'),
('A15', 'Tuberculose respiratória, com confirmação bacteriológica e histológica'),
('A37', 'Coqueluche'),
('A80', 'Poliomielite aguda'),
('A90', 'Dengue [dengue clássico]'),
('B05', 'Sarampo'),
('B24', 'Doença pelo vírus da imunodeficiência humana [HIV] não especificada'),
('B34', 'Doença por vírus de localização não especificada'),
('C18', 'Neoplasia maligna do cólon'),
('C34', 'Neoplasia maligna dos brônquios e dos pulmões'),
('C50', 'Neoplasia maligna da mama'),
('C53', 'Neoplasia maligna do colo do útero'),
('D50', 'Anemia por deficiência de ferro'),
('D64', 'Outras anemias'),
('E10', 'Diabetes mellitus insulino-dependente'),
('E11', 'Diabetes mellitus não-insulino-dependente'),
('E66', 'Obesidade'),
('F10', 'Transtornos mentais e comportamentais devidos ao uso de álcool'),
('F20', 'Esquizofrenia'),
('F31', 'Transtorno afetivo bipolar'),
('F32', 'Episódios depressivos'),
('F41', 'Outros transtornos ansiosos'),
('G40', 'Epilepsia'),
('G43', 'Enxaqueca'),
('G47', 'Distúrbios do sono'),
('H25', 'Catarata senil'),
('H52', 'Transtornos da refração e da acomodação'),
('I10', 'Hipertensão essencial (primária)'),
('I20', 'Angina pectoris'),
('I21', 'Infarto agudo do miocárdio'),
('I25', 'Doença isquêmica crônica do coração'),
('I50', 'Insuficiência cardíaca'),
('I64', 'Acidente vascular cerebral, não especificado como hemorrágico ou isquêmico'),
('J06', 'Infecções agudas das vias aéreas superiores de localizações múltiplas e não especificadas'),
('J18', 'Pneumonia por microorganismo não especificado'),
('J30', 'Rinite alérgica e vasomotora'),
('J44', 'Outras doenças pulmonares obstrutivas crônicas'),
('J45', 'Asma'),
('K25', 'Úlcera gástrica'),
('K29', 'Gastrite e duodenite'),
('K74', 'Fibrose e cirrose hepáticas'),
('K80', 'Colelitíase'),
('L20', 'Dermatite atópica'),
('L70', 'Acne'),
('M17', 'Gonartrose [artrose do joelho]'),
('M19', 'Outras artroses'),
('M47', 'Espondilose'),
('M51', 'Outros transtornos de discos intervertebrais'),
('M54', 'Dorsalgia'),
('M79', 'Outros transtornos dos tecidos moles, não classificados em outra parte'),
('N18', 'Insuficiência renal crônica'),
('N30', 'Cistite'),
('N39', 'Outros transtornos do aparelho urinário'),
('N40', 'Hiperplasia da próstata'),
('O80', 'Parto único espontâneo'),
('R05', 'Tosse'),
('R07', 'Dor de garganta e no peito'),
('R10', 'Dor abdominal e pélvica'),
('R42', 'Tontura e vertigem'),
('R50', 'Febre de origem desconhecida'),
('R51', 'Cefaléia'),
('S06', 'Traumatismo intracraniano'),
('S52', 'Fratura do antebraço'),
('S62', 'Fratura ao nível do punho e da mão'),
('S72', 'Fratura do fêmur'),
('S82', 'Fratura da perna, incluindo tornozelo'),
('Z00', 'Exame geral e investigação de pessoas sem queixas ou diagnóstico relatado'),
('Z38', 'Nascido vivo, único, segundo o local de nascimento'),
('Z47', 'Outros cuidados posteriores ortopédicos'),
('B00', 'Infecções pelo vírus do herpes'),
('B01', 'Varicela'),
('B02', 'Herpes zoster'),
('B07', 'Verrugas de origem viral'),
('B08', 'Outras infecções virais caracterizadas por lesões de pele e das mucosas'),
('B15', 'Hepatite aguda A'),
('B16', 'Hepatite aguda B'),
('B17', 'Outras hepatites virais agudas'),
('B18', 'Hepatite viral crônica'),
('B26', 'Caxumba'),
('B27', 'Mononucleose infecciosa'),
('C43', 'Melanoma maligno da pele'),
('C44', 'Outras neoplasias malignas da pele'),
('C61', 'Neoplasia maligna da próstata'),
('C67', 'Neoplasia maligna da bexiga'),
('C81', 'Linfoma de Hodgkin'),
('C91', 'Leucemia linfóide'),
('C92', 'Leucemia mielóide'),
('E03', 'Outros hipotireoidismos'),
('E05', 'Tireotoxicose [hipertireoidismo]'),
('E78', 'Distúrbios do metabolismo de lipoproteínas e outras lipidemias'),
('F00', 'Demência na doença de Alzheimer'),
('F03', 'Demência não especificada'),
('F40', 'Transtornos fóbico-ansiosos'),
('F43', 'Reações ao "stress" grave e transtornos de adaptação'),
('F50', 'Transtornos da alimentação'),
('F60', 'Transtornos específicos da personalidade'),
('F70', 'Retardo mental leve'),
('F84', 'Transtornos globais do desenvolvimento'),
('F90', 'Transtornos hipercinéticos'),
('G20', 'Doença de Parkinson'),
('G35', 'Esclerose múltipla'),
('G45', 'Ataques isquêmicos cerebrais transitórios e síndromes correlatas'),
('G56', 'Mononeuropatias dos membros superiores'),
('G62', 'Outras polineuropatias'),
('H10', 'Conjuntivite'),
('H35', 'Outros transtornos da retina'),
('H40', 'Glaucoma'),
('H81', 'Transtornos da função vestibular'),
('H90', 'Perda de audição por transtorno de condução e/ou neuro-sensorial'),
('I35', 'Transtornos não-reumáticos da valva aórtica'),
('I48', '"Fibrilação" e "flutter" atrial'),
('I63', 'Infarto cerebral'),
('I70', 'Aterosclerose'),
('I73', 'Outras doenças vasculares periféricas'),
('I83', 'Varizes dos membros inferiores'),
('I84', 'Hemorróidas'),
('J02', 'Faringite aguda'),
('J03', 'Amigdalite aguda'),
('J11', 'Influenza [gripe] com pneumonia, vírus não identificado'),
('J20', 'Bronquite aguda'),
('J32', 'Sinusite crônica'),
('J42', 'Bronquite crônica não especificada'),
('K02', 'Cárie dentária'),
('K05', 'Gengivite e doenças periodontais'),
('K21', 'Doença de refluxo gastroesofágico'),
('K35', 'Apendicite aguda'),
('K57', 'Doença diverticular do intestino'),
('K58', 'Síndrome do cólon irritável'),
('K60', 'Fissura e fístula anais e retais'),
('K85', 'Pancreatite aguda'),
('L02', 'Abscesso cutâneo, furúnculo e carbúnculo'),
('L03', 'Celulite'),
('L30', 'Outras dermatites'),
('L40', 'Psoríase'),
('L60', 'Afecções das unhas'),
('L89', 'Úlcera de decúbito'),
('M05', 'Artrite reumatóide soro-positiva'),
('M06', 'Outras artrites reumatóides'),
('M10', 'Gota'),
('M15', 'Poliartrose'),
('M16', 'Coxartrose [artrose do quadril]'),
('M23', 'Transtornos internos dos joelhos'),
('M25', 'Outras doenças articulares não classificadas em outra parte'),
('M32', 'Lúpus eritematoso sistêmico'),
('M65', 'Sinovite e tenossinovite'),
('M75', 'Lesões do ombro'),
('M77', 'Outras entesopatias'),
('M81', 'Osteoporose sem fratura patológica'),
('N10', 'Nefrite túbulo-intersticial aguda'),
('N20', 'Calculose do rim e do ureter'),
('N60', 'Displasias mamárias benignas'),
('N76', 'Outras afecções inflamatórias da vagina e da vulva'),
('N80', 'Endometriose'),
('N92', 'Menstruação excessiva, freqüente e irregular'),
('O20', 'Hemorragia do início da gravidez'),
('O36', 'Assistência prestada à mãe por outros problemas ligados à gravidez'),
('O48', 'Gravidez prolongada'),
('O60', 'Trabalho de parto pré-termo'),
('P07', 'Transtornos relacionados com a gestação de curta duração e com baixo peso ao nascer'),
('Q05', 'Espinha bífida'),
('Q66', 'Deformidades congênitas do pé'),
('R00', 'Anormalidades do batimento cardíaco'),
('R11', 'Náusea e vômitos'),
('R19', 'Outros sintomas e sinais relativos ao aparelho digestivo e ao abdome'),
('R21', 'Eritema e outras erupções cutâneas não especificadas'),
('R52', 'Dor não classificada em outra parte'),
('R53', 'Mal estar, fadiga'),
('R63', 'Sintomas e sinais relativos à ingestão de alimentos e líquidos'),
('S00', 'Traumatismo superficial da cabeça'),
('S01', 'Ferimento da cabeça'),
('S03', 'Luxação, entorse e distensão das articulações e dos ligamentos da cabeça'),
('S13', 'Luxação, entorse e distensão das articulações e dos ligamentos do pescoço'),
('S22', 'Fratura de costela(s), esterno e coluna torácica'),
('S32', 'Fratura da coluna lombar e da pelve'),
('S42', 'Fratura do ombro e do braço'),
('S92', 'Fratura do pé, exceto artelho'),
('T14', 'Traumatismo de região não especificada do corpo'),
('T20', 'Queimadura e corrosão da cabeça e pescoço'),
('T23', 'Queimadura e corrosão do punho e da mão'),
('T30', 'Queimadura e corrosão, parte do corpo não especificada'),
('Z01', 'Outros exames especiais e investigações de pessoas sem queixa ou diagnóstico relatado'),
('Z03', 'Observação e avaliação médicas por suspeita de doenças e afecções'),
('Z21', 'Estado de infecção assintomática pelo vírus da imunodeficiência humana [HIV]'),
('Z34', 'Supervisão de gravidez normal'),
('Z51', 'Outros cuidados médicos'),
('Z71', 'Pessoas em contato com os serviços de saúde para outros aconselhamentos e conselhos médicos'),
('Z72', 'Problemas relacionados com o estilo de vida'),
('Z86', 'História pessoal de algumas outras doenças'),
('Z99', 'Dependência de máquinas e aparelhos capacitantes, não classificada em outra parte'),
('A01', 'Febres tifóide e paratifóide'),
('A02', 'Outras infecções por Salmonella'),
('A04', 'Outras infecções intestinais bacterianas'),
('A06', 'Amebíase'),
('A16', 'Tuberculose das vias respiratórias, sem confirmação bacteriológica ou histológica'),
('A22', 'Carbúnculo'),
('A30', 'Hanseníase [lepra]'),
('A36', 'Difteria'),
('A39', 'Infecção meningocócica'),
('A41', 'Outras septicemias'),
('A54', 'Infecção gonocócica'),
('A82', 'Raiva'),
('A92', 'Outras febres por mosquitos'),
('B06', 'Rubéola'),
('B20', 'Doença pelo HIV resultando em doenças infecciosas e parasitárias'),
('B25', 'Doença por citomegalovírus'),
('B50', 'Malária por Plasmodium falciparum'),
('B58', 'Toxoplasmose'),
('C00', 'Neoplasia maligna do lábio'),
('C11', 'Neoplasia maligna da nasofaringe'),
('C15', 'Neoplasia maligna do esôfago'),
('C16', 'Neoplasia maligna do estômago'),
('C22', 'Neoplasia maligna do fígado e das vias biliares intra-hepáticas'),
('C25', 'Neoplasia maligna do pâncreas'),
('C64', 'Neoplasia maligna do rim, exceto pelve renal'),
('C71', 'Neoplasia maligna do encéfalo'),
('D12', 'Neoplasia benigna do cólon, reto, ânus e canal anal'),
('D22', 'Nevos melanocíticos'),
('D69', 'Púrpura e outras afecções hemorrágicas'),
('E16', 'Outros transtornos da secreção pancreática interna'),
('E22', 'Hiperfunção da hipófise'),
('E44', 'Desnutrição protéico-calórica de graus moderado e leve'),
('F06', 'Outros transtornos mentais devidos a lesão e disfunção cerebral e a doença física'),
('F44', 'Transtornos dissociativos [de conversão]'),
('G30', 'Doença de Alzheimer'),
('G80', 'Paralisia cerebral');

