ALTER TABLE municipio
    ADD COLUMN IF NOT EXISTS discoverable BOOLEAN DEFAULT TRUE,
    ADD COLUMN IF NOT EXISTS base_url VARCHAR(255),
    ADD COLUMN IF NOT EXISTS public_key TEXT,
    ADD COLUMN IF NOT EXISTS api_key VARCHAR(100) UNIQUE;

